### ISSUE TITLE
Initial structure commited to branch

### ISSUE THREAD

**Issue by hurjun1995** [hurjun1995/JJCo#1]
Take a look at the initial structure I've implemented in the branch; I did api for email and facebook register, and implemented the Welcome UI. I didn't fully connect it to api yet.

**Comment by leesw98** [comment]
Still reading through because its a big commit but I see DS_STORE files in the log. You might want to add it into the .gitignore

**Comment by leesw98** [comment]
Also perhaps you should make this into a pr? so I can leave comments if necessary or any questions I have
